### ISSUE TITLE
Consider adding tracker data types for CVE maintenance

### ISSUE THREAD

**Issue by Chris-Turner-NIST** [usnistgov/vulntology#30]
# User Story:

Throughout the Vulnerability life cycle there are a series of events that would be valuable to track for historical, maintenance and academic purposes. Should we consider adding these types of information?

Ex: 
ID Date
Public Disclosure Date
Patched Date 
etc.

Many examples of this can be found within the CVRF documentation

## Goals:

Review important data types that are useful for historical, academic and program maintenance. Provide either a new object and properties or series of properties that should be associated to an existing object.
Update all documentation to reflect the additional data types.

## Dependencies:

N/A

## Acceptance Criteria

- [ ] Identify all desired data types for tracking of each use case
- [ ] Creation of appropriate Object/s, Properties and Relationships
- [ ] A Pull Request (PR) is submitted that addresses the goals of this User Story. This issue is referenced in the PR. If the PR only partially addresses a given User Story, the specific goals addressed are identified in the PR.
- [ ] All graphs, visuals and figures updated to reflect changes
