### ISSUE TITLE
Add constraints within JSON Schema

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/vulntology#58]
# User Story:

As a Vulntology JSON content creator, I need a way to enforce specific co-constraints.

## Goals:

Implement the following co-constraints in the JSON schema if possible.
- [x] For impacts, `gainedPrivileges` should only be allowed when the property `hasLogicalImpact` is `Logical Impact::Privilege Escalation`. See #72.
- [x] Has `hasLocation` should only be optionally allowed when a `hasLogicalImpact` is defined. See #72.
- [x] For barriers, `neededPrivileges` must be provided when `blockedByBarrier` is `Authentication/Authorization::Privileges Required`. See #85.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that addresses the goals of this User Story. This issue is referenced in the PR. If the PR only partially addresses a given User Story, the specific goals addressed are identified in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}
